USE Swiggy;

-- SELECT all records from the restaurants table.

SELECT * FROM restaurants LIMIT 100;

-- Rank every restaurant from most expensive to least expensive.

SELECT *, RANK() OVER(ORDER BY cost DESC) FROM restaurants;

-- Rank every restaurant from most visited to least visited.

SELECT *, RANK() OVER(ORDER BY rating_count DESC) FROM restaurants;

-- Rank every restaurant from most expensive to least expensive as per their city.

SELECT *, RANK()
 OVER(PARTITION BY city
 ORDER BY cost DESC)
 FROM restaurants;

-- Dense-rank every restaurant from most expensive to least expensive as per their city.

SELECT *, DENSE_RANK()
OVER(PARTITION BY city 
ORDER BY cost DESC)
FROM restaurants; 

-- Row-number every restaurant from most expensive to least expensive as per their city.

SELECT *, ROW_NUMBER()
OVER(PARTITION BY city 
ORDER BY cost DESC)
FROM restaurants; 

-- Rank the restaurant based on their prices (most to least expensive) as per cuisine using rank, dense_rank, and row_number.

SELECT *, RANK()
 OVER(PARTITION BY cuisine
 ORDER BY cost DESC)
 FROM restaurants;

-- Find top 5 restaurants of every city as per their revenue.

SELECT * FROM (
    SELECT *, RANK() 
    OVER(PARTITION BY city 
    ORDER BY cost * rating_count DESC) AS Revenue_Rank 
    FROM restaurants 
) AS Ranked
WHERE Revenue_Rank = 5;

-- Find top 5 restaurants of every cuisine as per their revenue.

SELECT * FROM (
SELECT *, RANK()
OVER(PARTITION BY city ORDER BY cuisine DESC) AS Revenue_Rank
FROM restaurants
) AS Ranked
WHERE Revenue_Rank = 5;

-- List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine.

-- List the top 5 cities as per the revenue generated by top 5 restaurants of every city.

-- Find the total revenue generated by top 1% restaurants.

-- Find the total revenue generated by top 20% restaurants.

-- What percentage of total revenue is generated by top 20% restaurants?
